#!/usr/bin/env python3
"""health_piper — Piper arm health primitive.

Reads Piper arm joint motor temperatures, error codes, enable states, and
arm-level safety status via piper_sdk on a CAN bus, then streams them as
HealthState frames over robonix/primitive/health/stream (gRPC server_stream).

SOMA discovers this primitive through Atlas and consumes the stream to
build SomaHealthSnapshot for Vitals.

Requires: piper-sdk >= 0.6.1 (installed in ~/roboarm/.venv).
"""

from __future__ import annotations

import logging
import time
from typing import Iterator

from robonix_api import Primitive, Ok, Err

# ── piper_sdk import (from roboarm venv) ──────────────────────────────
try:
    from piper_sdk import C_PiperInterface_V2

    PIPER_AVAILABLE = True
except ImportError:
    PIPER_AVAILABLE = False

# ── Codegen stubs (generated by rbnx codegen) ─────────────────────────
import health_pb2

log = logging.getLogger("health_piper")

# ── Constants ─────────────────────────────────────────────────────────
JOINT_COUNT = 6
JOINT_NAMES = [f"joint_{i}" for i in range(1, JOINT_COUNT + 1)]

# foc_status bit → human-readable label (from piper_sdk CAN protocol).
# Bit 6 (0x40, driver_enable_status) is NOT a fault — it means the driver
# is enabled.  We exclude it from fault reporting.
FOC_FAULT_BITS: list[tuple[int, str, str]] = [
    # (bit, attr_name, human_label)
    (0, "voltage_too_low",      "电源电压过低"),
    (1, "motor_overheating",    "电机过温"),
    (2, "driver_overcurrent",   "驱动器过流"),
    (3, "driver_overheating",   "驱动器过温"),
    (4, "collision_status",     "碰撞保护触发"),
    (5, "driver_error_status",  "驱动器错误"),
    (7, "stall_status",         "堵转保护触发"),
]
# Bit 6 mask: only this bit → status code 0x40, meaning "driver enabled, no fault".
FOC_ENABLE_BIT = 0x40
FOC_FAULT_MASK = 0xBF  # all bits except driver_enable_status

# Arm status enum → safety aggregate_state (Soma SafetyState IDL).
# 0=NORMAL  1=FAULT  2=ESTOP
ARM_STATUS_TO_STATE = {
    0x00: 0,  # NORMAL
    0x01: 2,  # EMERGENCY_STOP     → ESTOP
    0x02: 1,  # NO_SOLUTION        → FAULT
    0x03: 1,  # SINGULARITY        → FAULT
    0x04: 1,  # TARGET_EXCEEDS     → FAULT
    0x05: 1,  # JOINT_COMM_ERR     → FAULT
    0x06: 1,  # BRAKE_NOT_OPEN     → FAULT
    0x07: 1,  # COLLISION          → FAULT
    0x08: 1,  # OVERSPEED          → FAULT
    0x09: 1,  # JOINT_STATUS_ERR   → FAULT
    0x0A: 1,  # OTHER              → FAULT
    0x0E: 1,  # MAIN_NTC_OVER_TEMP → FAULT
    0x0F: 1,  # RESISTOR_OVER_TEMP → FAULT
}

# ── Primitive ─────────────────────────────────────────────────────────

arm = Primitive(id="health_piper", namespace="robonix/primitive/health")

_can_port = "can0"


@arm.on_init
def init(cfg: dict):
    """Validate CAN port and piper_sdk availability."""
    global _can_port
    if not PIPER_AVAILABLE:
        return Err(
            "piper_sdk is not installed. Install piper-sdk>=0.6.1 "
            "in the Python environment (e.g. ~/roboarm/.venv)."
        )
    _can_port = cfg.get("can_port", "can0")
    # Quick connectivity check.
    try:
        piper = C_PiperInterface_V2(_can_port)
        piper.ConnectPort()
        log.info("health_piper: CAN port %s OK", _can_port)
    except Exception as e:
        return Err(f"Failed to open CAN port {_can_port}: {e}")
    return Ok()


@arm.on_activate
def activate():
    log.info("health_piper: activated on %s", _can_port)
    return Ok()


@arm.on_deactivate
def deactivate():
    log.info("health_piper: deactivated")
    return Ok()


# ── gRPC StreamHealthState handler ────────────────────────────────────


@arm.grpc("robonix/primitive/health/stream")
def stream_health(request, context) -> Iterator[health_pb2.HealthState]:
    """Server-stream: read Piper arm data, yield HealthState frames.

    Called by SOMA via gRPC.  Yields one frame per read cycle (~500 ms).
    Stops when the client disconnects or on_deactivate is called.
    """
    global _can_port

    try:
        piper = C_PiperInterface_V2(_can_port)
        piper.ConnectPort()
        log.info("health_piper: stream started on %s", _can_port)
    except Exception as e:
        log.error("health_piper: connect failed: %s", e)
        context.set_code(14)  # UNAVAILABLE
        context.set_details(str(e))
        return

    try:
        while context.is_active():
            yield _collect(piper)
            time.sleep(0.5)
    finally:
        log.info("health_piper: stream ended")


# ── Data collection ───────────────────────────────────────────────────


def _collect(piper: "C_PiperInterface_V2") -> health_pb2.HealthState:
    """Read Piper sensors and return a HealthState proto.

    FOC status codes are filtered: bit 6 (0x40, driver_enable_status) is
    masked out before reporting, because it indicates the driver is enabled
    rather than a fault condition.  Individual fault bits are reported as
    separate SensorReadings with human-readable labels in the name path.
    """
    temperatures: list[int] = []
    fault_codes: list[int] = []     # masked (bit 6 excluded)
    enables: list[bool] = []
    foc_statuses: list = []         # parsed FOC_Status objects for fault labels

    # Motor low-speed info (temperatures, error codes, enable states).
    try:
        low = piper.GetArmLowSpdInfoMsgs()
        motors = [
            low.motor_1, low.motor_2, low.motor_3,
            low.motor_4, low.motor_5, low.motor_6,
        ]
        for m in motors:
            temperatures.append(m.motor_temp)
            # Mask out bit 6 (driver_enable_status) — it is NOT a fault.
            fault_codes.append(m.foc_status_code & FOC_FAULT_MASK)
            enables.append(m.foc_status.driver_enable_status)
            foc_statuses.append(m.foc_status)
    except Exception:
        log.warning("health_piper: GetArmLowSpdInfoMsgs failed")
        for _ in range(JOINT_COUNT):
            temperatures.append(-1)
            fault_codes.append(0)
            enables.append(False)
            foc_statuses.append(None)

    # Arm-level status (safety state).
    arm_state = 1  # FAULT
    try:
        status = piper.GetArmStatus()
        raw = status.arm_status.arm_status
        arm_state = ARM_STATUS_TO_STATE.get(raw, 1)
    except Exception:
        log.warning("health_piper: GetArmStatus failed")

    # Build SensorReading list.
    readings: list[health_pb2.SensorReading] = []
    for i in range(JOINT_COUNT):
        path = f"body/arm/{JOINT_NAMES[i]}"
        # Motor temperature
        readings.append(health_pb2.SensorReading(
            name=f"{path}/motor_temp",
            temp_c=float(temperatures[i]),
        ))
        # Fault error code — only report when there are real fault bits
        # (bit 6 enable already masked out).
        if fault_codes[i] != 0:
            readings.append(health_pb2.SensorReading(
                name=f"{path}/error",
                current_a=float(fault_codes[i]),
            ))
        # Enable state
        readings.append(health_pb2.SensorReading(
            name=f"{path}/enabled",
            current_a=1.0 if enables[i] else 0.0,
        ))
        # Individual fault labels — one reading per active fault bit.
        if foc_statuses[i] is not None:
            foc = foc_statuses[i]
            for _bit, attr, label in FOC_FAULT_BITS:
                if getattr(foc, attr, False):
                    readings.append(health_pb2.SensorReading(
                        name=f"{path}/fault/{label}",
                        current_a=1.0,
                    ))

    # Arm-level safety state
    readings.append(health_pb2.SensorReading(
        name="body/arm/state",
        current_a=float(arm_state),
    ))

    return health_pb2.HealthState(
        voltage=-1.0,
        charging=False,
        remaining_s=-1,
        readings=readings,
    )


if __name__ == "__main__":
    arm.run()
